- name: Генерация и прокидывание SSH-ключа
  hosts: nextcloud_server
  become: true
  vars:
    user: user # Сменить имя юзера на актуальный
    backup_server_ip: 192.168.122.238  # Сменить ip на актуальный

  tasks:

    - name: Убедиться, что директория .ssh существует
      file:
        path: "/home/{{ user }}/.ssh"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0700'

    - name: Сгенерировать SSH-ключ (если не существует)
      openssh_keypair:
        path: "/home/{{ user }}/.ssh/id_rsa"
        type: rsa
        size: 4096
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0600'
      register: ssh_keygen
      args:
        creates: "/home/{{ user }}/.ssh/id_rsa"

    - name: Считать публичный ключ
      slurp:
        src: "/home/{{ user }}/.ssh/id_rsa.pub"
      register: pubkey_encoded

    - name: Преобразовать ключ в строку
      set_fact:
        pubkey: "{{ pubkey_encoded.content | b64decode }}"

    - name: Убедиться, что ключ добавлен на бэкап-сервер
      ansible.posix.authorized_key:
        user: "{{ user }}"
        key: "{{ pubkey }}"
        state: present
        manage_dir: true
      delegate_to: "{{ backup_server_ip }}"
